My Vensin: System Class Reference
System Class Reference
#include <System.h>
Public Member Functions
System (const std::string &name="NO_NAME", const double &value=0.0)
Construct a new System by name and value.
System (const System &other)
Construct a new System by a obj.
virtual ~System ()
This destructor is a virtual destructor of the Class.
std::string getName () const
This method returns the name of a system.
void setName (const std::string &name)
This method assigns a string to the name of a system.
double getValue () const
This method returns the value of a system.
void setValue (const double &value)
This method assigns a double to the value of a system.
System & operator= (const System &other)
This method is overloading the '=' operator, "cloning" from one system to another.
bool operator== (const System &other) const
This method is overloading the '==' operator, compare two systems objs.
Protected Attributes
std::string name
double value
Friends
std::ostream & operator<< (std::ostream &out, const System &obj)
This method is overloading the '<<' operator, print the system obj info.
Constructor & Destructor Documentation
System() [1/2]
System::System (const std::string & name = "NO_NAME", const double & value = 0.0)
Construct a new System by name and value.
Parameters
name string with default value "NO_NAME"
value double with default value 0.0
: name(name), value(value) {}
System() [2/2]
System::System (const System & other)
Construct a new System by a obj.
Parameters
other System obj
: name(other.name), value(other.value) {}
~System()
System::~System () virtual
This destructor is a virtual destructor of the Class.
{};
Member Function Documentation
getName()
std::string System::getName () const
This method returns the name of a system.
Returns
a string containing the name is returned
{ return name; }
References name.
getValue()
double System::getValue () const
This method returns the value of a system.
Returns
a double containing the value is returned
{ return value; }
References value.
Referenced by Complex_test_run(), Exponencial::execute(), Logistical::execute(), exponencial_test_run(), and logistical_test_run().
operator=()
System & System::operator= (const System & other)
This method is overloading the '=' operator, "cloning" from one system to another.
Parameters
other system obj to be cloned must be passed
Returns
A system is returned that is a clone of what was passed to the method
{
    if(other == *this) return *this;
    name = other.name;
    value = other.value;
    return *this;
}
References name, and value.
operator==()
bool System::operator== (const System & other) const
This method is overloading the '==' operator, compare two systems objs.
Parameters
other system obj to be compare must be passed
Returns
A bool is returned, true if they are equal and false if not
{
    return (name == other.name && value == other.value);
    // Compare todos os membros para verificar igualdade
}
References name, and value.
setName()
void System::setName (const std::string & name)
This method assigns a string to the name of a system.
Parameters
name string must be passed to the method
{ this->name = name; }
References name.
setValue()
void System::setValue (const double & value)
This method assigns a double to the value of a system.
Parameters
value double must be passed to the method
{ this->value = value; }
References value.
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & out, const System & obj) friend
This method is overloading the '<<' operator, print the system obj info.
Parameters
out is a ostream obj
obj is a system obj
Returns
a ostream obj to print the obj info
{
    out << "(System)(Name: " << obj.name << ", Value: " << obj.value << ")";
    return out;
}
Member Data Documentation
name
std::string System::name protected
Name string attribute.
Referenced by getName(), operator=(), operator==(), and setName().
value
double System::value protected
Value double attribute.
Referenced by getValue(), operator=(), operator==(), and setValue().
The documentation for this class was generated from the following files:
/home/pedro/Downloads/UFOP/Periodo6/EngSoftware1/Engenharia_de_Software1_tp1/src/System.h
/home/pedro/Downloads/UFOP/Periodo6/EngSoftware1/Engenharia_de_Software1_tp1/src/System.cpp