My Vensin: Model Class Reference
Model Class Reference abstract
#include <Model.hpp>
Public Types
typedef std::vector< System * >::iterator systemIterator
typedef System vetor iterator
typedef std::vector< Flow * >::iterator flowIterator
typedef Flow vetor iterator
Public Member Functions
virtual ~Model ()
This destructor is a virtual destructor of the class.
virtual std::string getName () const =0
This method returns the name of a Model.
virtual void setName (const std::string &name)=0
This method assigns a string to the name of a Model.
virtual std::vector< System * > getSystems () const =0
This method returns the vector of Systems.
virtual std::vector< Flow * > getFlows () const =0
This method returns the vector of flows.
virtual void setSystems (const std::vector< System * > systems)=0
This method assigns a vector to the systems of a Model.
virtual void setFlows (const std::vector< Flow * > flows)=0
This method assigns a vector to the flows of a Model.
virtual int getStartTime () const =0
This method returns the startTime of a Model.
virtual int getEndTime () const =0
This method returns the end of a Model.
virtual void setStartTime (const int &startTime)=0
This method assigns a int to the startTime of a Model.
virtual void setEndTime (const int &endTime)=0
This method assigns a int to the endTime of a Model.
virtual void setTime (const int &startTime, const int &endTime)=0
This method assigns a int to the startTime and endTime of a Model.
virtual void add (System *system)=0
This method add a System pointer to the vector of a Model.
virtual void add (Flow *flow)=0
This method add a Flow pointer to the vector of a Model.
virtual bool rmv (const System *system)=0
This method remove a System pointer of the vector of a Model.
virtual bool rmv (const Flow *flow)=0
This method remove a Flow pointer of the vector of a Model.
virtual bool run ()=0
This method run all model.
Member Typedef Documentation
flowIterator
typedef std::vector<Flow*>::iterator Model::flowIterator
typedef Flow vetor iterator
systemIterator
typedef std::vector<System*>::iterator Model::systemIterator
typedef System vetor iterator
Constructor & Destructor Documentation
~Model()
virtual Model::~Model () inline virtual
This destructor is a virtual destructor of the class.
{};
Referenced by test_Model_destructor().
Member Function Documentation
add() [1/2]
virtual void Model::add (Flow * flow) pure virtual
This method add a Flow pointer to the vector of a Model.
Parameters
flow Flow pointer must be passed to the method
Implemented in ModelIMP.
add() [2/2]
virtual void Model::add (System * system) pure virtual
This method add a System pointer to the vector of a Model.
Parameters
system System pointer must be passed to the method
Implemented in ModelIMP.
Referenced by Complex_test_run(), exponencial_test_run(), logistical_test_run(), test_Model_getFlows_and_add(), test_Model_getSystems_and_add(), test_Model_rmv_Flow(), test_Model_rmv_Sytem(), test_Model_run(), and test_MyVensim_run().
getEndTime()
virtual int Model::getEndTime () const pure virtual
This method returns the end of a Model.
Returns
a int containing the end is returned
Implemented in ModelIMP.
Referenced by test_Model_constructor(), test_Model_getEndTime(), test_Model_setEndTime(), and test_Model_setTime().
getFlows()
virtual std::vector< Flow * > Model::getFlows () const pure virtual
This method returns the vector of flows.
Returns
a vector containing Flows is returned
Implemented in ModelIMP.
Referenced by test_Model_getFlows_and_add(), and test_Model_setFlows().
getName()
virtual std::string Model::getName () const pure virtual
This method returns the name of a Model.
Returns
a string containing the name is returned
Implemented in ModelIMP.
Referenced by test_Model_constructor(), test_Model_getName(), and test_Model_setName().
getStartTime()
virtual int Model::getStartTime () const pure virtual
This method returns the startTime of a Model.
Returns
a int containing the startTime is returned
Implemented in ModelIMP.
Referenced by test_Model_constructor(), test_Model_getStartTime(), test_Model_setStartTime(), and test_Model_setTime().
getSystems()
virtual std::vector< System * > Model::getSystems () const pure virtual
This method returns the vector of Systems.
Returns
a vector containing Systems is returned
Implemented in ModelIMP.
Referenced by test_Model_getSystems_and_add(), and test_Model_setSystems().
rmv() [1/2]
virtual bool Model::rmv (const Flow * flow) pure virtual
This method remove a Flow pointer of the vector of a Model.
Parameters
flow Flow pointer iterator must be passed to the method
Returns
a bool value, true if can remove, false if not
Implemented in ModelIMP.
rmv() [2/2]
virtual bool Model::rmv (const System * system) pure virtual
This method remove a System pointer of the vector of a Model.
Parameters
system System pointer iterator must be passed to the method
Returns
a bool value, true if can remove, false if not
Implemented in ModelIMP.
Referenced by test_Model_rmv_Flow(), and test_Model_rmv_Sytem().
run()
virtual bool Model::run () pure virtual
This method run all model.
Returns
a bool value, true if can run, false if not
Implemented in ModelIMP.
Referenced by test_Model_run().
setEndTime()
virtual void Model::setEndTime (const int & endTime) pure virtual
This method assigns a int to the endTime of a Model.
Parameters
endTime int must be passed to the method
Implemented in ModelIMP.
Referenced by test_Model_setEndTime().
setFlows()
virtual void Model::setFlows (const std::vector< Flow * > flows) pure virtual
This method assigns a vector to the flows of a Model.
Parameters
flows int must be passed to the method
Implemented in ModelIMP.
Referenced by test_Model_setFlows().
setName()
virtual void Model::setName (const std::string & name) pure virtual
This method assigns a string to the name of a Model.
Parameters
name string must be passed to the method
Implemented in ModelIMP.
Referenced by test_Model_setName().
setStartTime()
virtual void Model::setStartTime (const int & startTime) pure virtual
This method assigns a int to the startTime of a Model.
Parameters
startTime int must be passed to the method
Implemented in ModelIMP.
Referenced by test_Model_setStartTime().
setSystems()
virtual void Model::setSystems (const std::vector< System * > systems) pure virtual
This method assigns a vector to the systems of a Model.
Parameters
systems int must be passed to the method
Implemented in ModelIMP.
Referenced by test_Model_setSystems().
setTime()
virtual void Model::setTime (const int & startTime, const int & endTime) pure virtual
This method assigns a int to the startTime and endTime of a Model.
Parameters
startTime int must be passed to the method
endTime int must be passed to the method
Implemented in ModelIMP.
Referenced by test_Model_setTime().
The documentation for this class was generated from the following file:
/home/pedro/Downloads/UFOP/Periodo6/EngSoftware1/Engenharia_de_Software1_tp1/src/Model.hpp