My Vensin: MyVensim Class Reference
MyVensim Class Reference abstract
#include <MyVensim.hpp>
Public Types
typedef std::vector< System * >::iterator systemIterator
typedef System vetor iterator
typedef std::vector< Flow * >::iterator flowIterator
typedef Flow vetor iterator
typedef std::vector< Model * >::iterator modelIterator
typedef Model vetor iterator
Public Member Functions
virtual ~MyVensim ()
This destructor is a virtual destructor of the class.
virtual System * createSystem (const std::string &name="NO_NAME", const double &value=0.0)=0
Create a instance of System.
template<typename FlowType >
Flow * createFlow (const std::string name="NONAME", System *source=nullptr, System *destiny=nullptr)
Create a instance of Flow.
virtual Model * createModel (const std::string &name="NO_NAME", const int &startTime=0, const int &endTime=1)=0
Create a instance of Model.
virtual void add (System *system)=0
This method add a System pointer to the vector.
virtual void add (Flow *flow)=0
This method add a Flow pointer to the vector.
virtual void add (Model *model)=0
This method add a Model pointer to the vector.
virtual bool rmv (const System *system)=0
This method remove a System pointer of the vector.
virtual bool rmv (const Flow *flow)=0
This method remove a Flow pointer of the vector.
virtual bool rmv (const Model *model)=0
This method remove a Model pointer of the vector.
virtual std::string getName () const =0
This method returns the name of a MyVensim.
virtual void setName (const std::string &name)=0
This method assigns a string to the name of a MyVensim.
virtual std::vector< System * > getSystems () const =0
This method returns the vector of Systems.
virtual std::vector< Flow * > getFlows () const =0
This method returns the vector of flows.
virtual std::vector< Model * > getModels () const =0
This method returns the vector of Models.
virtual void setSystems (const std::vector< System * > systems)=0
This method assigns a vector to the systems of a MyVensim.
virtual void setFlows (const std::vector< Flow * > flows)=0
This method assigns a vector to the flows of a MyVensim.
virtual void setModels (const std::vector< Model * > models)=0
This method assigns a vector to the models of a MyVensim.
virtual bool run ()=0
This method run all model.
Member Typedef Documentation
flowIterator
typedef std::vector<Flow*>::iterator MyVensim::flowIterator
typedef Flow vetor iterator
modelIterator
typedef std::vector<Model*>::iterator MyVensim::modelIterator
typedef Model vetor iterator
systemIterator
typedef std::vector<System*>::iterator MyVensim::systemIterator
typedef System vetor iterator
Constructor & Destructor Documentation
~MyVensim()
virtual MyVensim::~MyVensim () inline virtual
This destructor is a virtual destructor of the class.
{}
Referenced by test_MyVensim_destructor().
Member Function Documentation
add() [1/3]
virtual void MyVensim::add (Flow * flow) pure virtual
This method add a Flow pointer to the vector.
Parameters
flow Flow pointer must be passed to the method
Implemented in MyVensimIMP.
add() [2/3]
virtual void MyVensim::add (Model * model) pure virtual
This method add a Model pointer to the vector.
Parameters
model Model pointer must be passed to the method
Implemented in MyVensimIMP.
add() [3/3]
virtual void MyVensim::add (System * system) pure virtual
This method add a System pointer to the vector.
Parameters
system System pointer must be passed to the method
Implemented in MyVensimIMP.
Referenced by createFlow(), test_MyVensim_rmv_Flow(), test_MyVensim_rmv_Model(), and test_MyVensim_rmv_Sytem().
createFlow()
template<typename FlowType > Flow * MyVensim::createFlow (const std::string name = "NONAME", System * source = nullptr, System * destiny = nullptr) inline
Create a instance of Flow.
Parameters
name string with default value "NO_NAME"
source System pointer with default value NULL
target System pointer with default value NULL
Returns
A Flow pointer to the new instance of Flow
{
            Flow* f = new FlowType(name, source, destiny);
            add(f);
            return f;
        }
References add().
Referenced by Complex_test_run(), exponencial_test_run(), logistical_test_run(), test_MyVensim_getFlows_and_add(), and test_MyVensim_run().
createModel()
virtual Model * MyVensim::createModel (const std::string & name = "NO_NAME", const int & startTime = 0, const int & endTime = 1) pure virtual
Create a instance of Model.
Parameters
name string with default value "NO_NAME"
startTime int with default value 0
endTime int with default value 1
Returns
A Model pointer to the new instance of Model
Implemented in MyVensimIMP.
Referenced by Complex_test_run(), exponencial_test_run(), logistical_test_run(), test_MyVensim_getModels_and_add(), and test_MyVensim_run().
createSystem()
virtual System * MyVensim::createSystem (const std::string & name = "NO_NAME", const double & value = 0.0) pure virtual
Create a instance of System.
Parameters
name string with default value "NO_NAME"
value double with default value 0.0
Returns
A System pointer to the new instance of System
Implemented in MyVensimIMP.
Referenced by Complex_test_run(), exponencial_test_run(), logistical_test_run(), test_MyVensim_getSystems_and_add(), and test_MyVensim_run().
getFlows()
virtual std::vector< Flow * > MyVensim::getFlows () const pure virtual
This method returns the vector of flows.
Returns
a vector containing Flows is returned
Implemented in MyVensimIMP.
Referenced by test_MyVensim_getFlows_and_add(), and test_MyVensim_setFlows().
getModels()
virtual std::vector< Model * > MyVensim::getModels () const pure virtual
This method returns the vector of Models.
Returns
a vector containing Models is returned
Implemented in MyVensimIMP.
Referenced by test_MyVensim_getModels_and_add(), and test_MyVensim_setModels().
getName()
virtual std::string MyVensim::getName () const pure virtual
This method returns the name of a MyVensim.
Returns
a string containing the name is returned
Implemented in MyVensimIMP.
Referenced by test_MyVensim_constructor(), test_MyVensim_getName(), and test_MyVensim_setName().
getSystems()
virtual std::vector< System * > MyVensim::getSystems () const pure virtual
This method returns the vector of Systems.
Returns
a vector containing Systems is returned
Implemented in MyVensimIMP.
Referenced by test_MyVensim_getSystems_and_add(), and test_MyVensim_setSystems().
rmv() [1/3]
virtual bool MyVensim::rmv (const Flow * flow) pure virtual
This method remove a Flow pointer of the vector.
Parameters
flow Flow pointer iterator must be passed to the method
Returns
a bool value, true if can remove, false if not
Implemented in MyVensimIMP.
rmv() [2/3]
virtual bool MyVensim::rmv (const Model * model) pure virtual
This method remove a Model pointer of the vector.
Parameters
model Model pointer iterator must be passed to the method
Returns
a bool value, true if can remove, false if not
Implemented in MyVensimIMP.
rmv() [3/3]
virtual bool MyVensim::rmv (const System * system) pure virtual
This method remove a System pointer of the vector.
Parameters
system System pointer iterator must be passed to the method
Returns
a bool value, true if can remove, false if not
Implemented in MyVensimIMP.
Referenced by test_MyVensim_rmv_Flow(), test_MyVensim_rmv_Model(), and test_MyVensim_rmv_Sytem().
run()
virtual bool MyVensim::run () pure virtual
This method run all model.
Returns
a bool value, true if can run, false if not
Implemented in MyVensimIMP.
Referenced by Complex_test_run(), exponencial_test_run(), logistical_test_run(), and test_MyVensim_run().
setFlows()
virtual void MyVensim::setFlows (const std::vector< Flow * > flows) pure virtual
This method assigns a vector to the flows of a MyVensim.
Parameters
flows int must be passed to the method
Implemented in MyVensimIMP.
Referenced by test_MyVensim_setFlows().
setModels()
virtual void MyVensim::setModels (const std::vector< Model * > models) pure virtual
This method assigns a vector to the models of a MyVensim.
Parameters
models int must be passed to the method
Implemented in MyVensimIMP.
Referenced by test_MyVensim_setModels().
setName()
virtual void MyVensim::setName (const std::string & name) pure virtual
This method assigns a string to the name of a MyVensim.
Parameters
name string must be passed to the method
Implemented in MyVensimIMP.
Referenced by test_MyVensim_setName().
setSystems()
virtual void MyVensim::setSystems (const std::vector< System * > systems) pure virtual
This method assigns a vector to the systems of a MyVensim.
Parameters
systems int must be passed to the method
Implemented in MyVensimIMP.
Referenced by test_MyVensim_setSystems().
The documentation for this class was generated from the following file:
/home/pedro/Downloads/UFOP/Periodo6/EngSoftware1/Engenharia_de_Software1_tp1/src/MyVensim.hpp