My Vensin: Flow Class Reference
Flow Class Reference abstract
#include <Flow.h>
Public Member Functions
virtual ~Flow ()
This destructor is a virtual destructor of the class.
virtual std::string getName () const =0
This method returns the name of a flow.
virtual void setName (const std::string &name)=0
This method assigns a string to the name of a flow obj.
virtual System * getSource () const =0
This method returns the source system poiter.
virtual void setSource (System *source)=0
This method assigns a system poiter to the source of a flow obj.
virtual System * getTarget () const =0
This method returns the target system poiter.
virtual void setTarget (System *target)=0
This method assigns a system poiter to the target of a flow obj.
virtual double execute ()=0
Pure virtual method that will be inherited by subclasses created by the user, this one will contain an equation that will be executed in the flow by the model.
Constructor & Destructor Documentation
~Flow()
virtual Flow::~Flow () inline virtual
This destructor is a virtual destructor of the class.
{};
Referenced by test_Flow_destructor().
Member Function Documentation
execute()
virtual double Flow::execute () pure virtual
Pure virtual method that will be inherited by subclasses created by the user, this one will contain an equation that will be executed in the flow by the model.
Returns
double
Implemented in Exponencial, Logistical, Flow_unit_test, and FlowIMP.
Referenced by test_Flow_execute().
getName()
virtual std::string Flow::getName () const pure virtual
This method returns the name of a flow.
Returns
a string containing the name is returned
Implemented in FlowIMP.
Referenced by test_Flow_constructor(), test_Flow_getName(), and test_Flow_setName().
getSource()
virtual System * Flow::getSource () const pure virtual
This method returns the source system poiter.
Returns
a system poiter containing the source memory address is returned
Implemented in FlowIMP.
Referenced by test_Flow_constructor(), test_Flow_execute(), test_Flow_getSource(), and test_Flow_setSource().
getTarget()
virtual System * Flow::getTarget () const pure virtual
This method returns the target system poiter.
Returns
a system poiter containing the target memory address is returned
Implemented in FlowIMP.
Referenced by test_Flow_constructor(), test_Flow_execute(), test_Flow_getTarget(), and test_Flow_setTarget().
setName()
virtual void Flow::setName (const std::string & name) pure virtual
This method assigns a string to the name of a flow obj.
Parameters
name string must be passed to the method
Implemented in FlowIMP.
Referenced by test_Flow_setName().
setSource()
virtual void Flow::setSource (System * source) pure virtual
This method assigns a system poiter to the source of a flow obj.
Parameters
source system poiter must be passed to the method
Implemented in FlowIMP.
Referenced by test_Flow_setSource().
setTarget()
virtual void Flow::setTarget (System * target) pure virtual
This method assigns a system poiter to the target of a flow obj.
Parameters
target system poiter must be passed to the method
Implemented in FlowIMP.
Referenced by test_Flow_setTarget().
The documentation for this class was generated from the following file:
/home/pedro/Downloads/UFOP/Periodo6/EngSoftware1/Engenharia_de_Software1_tp1/src/Flow.h