My Vensin: /home/pedro/Downloads/UFOP/Periodo6/EngSoftware1/Engenharia_de_Software1_tp1/tests/functional_tests/src/main.cpp File Reference
main.cpp File Reference
#include "Functional_tests.hpp"
Functions
int main ()
Function Documentation
main()
int main ()
          {
    std::cout << "\nStart functional tests\n"
              << "*******************************************************\n";
    exponencial_test_run();
    logistical_test_run();
    Complex_test_run();
    std::cout << "*******************************************************\n"
              << "End functional tests\n\n";
    return 0;
}
References Complex_test_run(), exponencial_test_run(), and logistical_test_run().