My Vensin: /home/pedro/Downloads/UFOP/Periodo6/EngSoftware1/Engenharia_de_Software1_tp1/tests/unit_tests/src/unit_Model.hpp File Reference
unit_Model.hpp File Reference
#include "../../../src/FlowIMP.hpp"
#include "../../../src/SystemIMP.hpp"
#include "../../../src/ModelIMP.hpp"
#include "unit_Flow.hpp"
#include <assert.h>
Functions
void test_Model_constructor ()
This function run the unit test of the model constructor.
void test_Model_destructor ()
This function run the unit test of the model destructor.
void test_Model_getName ()
This function run the unit test of the model getName.
void test_Model_getSystems_and_add ()
This function run the unit test of the model getSystems and add System.
void test_Model_getFlows_and_add ()
This function run the unit test of the model getFlows and add Flow.
void test_Model_getStartTime ()
This function run the unit test of the model getStartTime.
void test_Model_getEndTime ()
This function run the unit test of the model getEndTime.
void test_Model_setName ()
This function run the unit test of the model setName.
void test_Model_setSystems ()
This function run the unit test of the model setSystems.
void test_Model_setFlows ()
This function run the unit test of the model setFlows.
void test_Model_setStartTime ()
This function run the unit test of the model setStartTime.
void test_Model_setEndTime ()
This function run the unit test of the model setEndTime.
void test_Model_setTime ()
This function run the unit test of the model setTime.
void test_Model_rmv_Sytem ()
This function run the unit test of the model rmv System.
void test_Model_rmv_Flow ()
This function run the unit test of the model rmv Flow.
void test_Model_equal ()
This function run the unit test of the model equal.
void test_Model_run ()
This function run the unit test of the model run.
void run_Model_unit_test ()
This function run the unit tests of the model.
Function Documentation
run_Model_unit_test()
void run_Model_unit_test ()
This function run the unit tests of the model.
{
    std::cout << "    Start Model unit tests\n";
    test_Model_constructor();
    test_Model_destructor();
    test_Model_getName();
    test_Model_getSystems_and_add();
    test_Model_getFlows_and_add();
    test_Model_getStartTime();
    test_Model_getEndTime();
    test_Model_setName();
    test_Model_setSystems();
    test_Model_setFlows();
    test_Model_setStartTime();
    test_Model_setEndTime();
    test_Model_setTime();
    test_Model_rmv_Sytem();
    test_Model_rmv_Flow();
    test_Model_run();
    test_Model_equal();
    std::cout << "    End Model unit tests\n\n";
}
References test_Model_constructor(), test_Model_destructor(), test_Model_equal(), test_Model_getEndTime(), test_Model_getFlows_and_add(), test_Model_getName(), test_Model_getStartTime(), test_Model_getSystems_and_add(), test_Model_rmv_Flow(), test_Model_rmv_Sytem(), test_Model_run(), test_Model_setEndTime(), test_Model_setFlows(), test_Model_setName(), test_Model_setStartTime(), test_Model_setSystems(), and test_Model_setTime().
Referenced by main().
test_Model_constructor()
void test_Model_constructor ()
This function run the unit test of the model constructor.
{
    std::cout << "        * Constructor tests\n";
    Model* m1 = new ModelIMP();
    assert(m1->getName() == "NO_NAME");
    assert(m1->getStartTime() == 0);
    assert(m1->getEndTime() == 1);
    Model* m2 = new ModelIMP("m2");
    assert(m2->getName() == "m2");
    assert(m2->getStartTime() == 0);
    assert(m2->getEndTime() == 1);
    Model* m3 = new ModelIMP("m3", 2);
    assert(m3->getName() == "m3");
    assert(m3->getStartTime() == 2);
    assert(m3->getEndTime() == 1);
    Model* m4 = new ModelIMP("m4", 2, 5);
    assert(m4->getName() == "m4");
    assert(m4->getStartTime() == 2);
    assert(m4->getEndTime() == 5);
    delete m1;
    delete m2;
    delete m3;
    delete m4;
}
References Model::getEndTime(), Model::getName(), and Model::getStartTime().
Referenced by run_Model_unit_test().
test_Model_destructor()
void test_Model_destructor ()
This function run the unit test of the model destructor.
{
    std::cout << "        * Destructor tests\n";
    Model* m1 = new ModelIMP();
    m1->~Model();
}
References Model::~Model().
Referenced by run_Model_unit_test().
test_Model_equal()
void test_Model_equal ()
This function run the unit test of the model equal.
                       {
    std::cout << "        * Equal tests\n";
    ModelIMP* m1 = new ModelIMP();
    ModelIMP* m2 = new ModelIMP();
    assert(*m1 == *m2);
    m1->setName("m1");
    assert(m1 != m2);
    delete m1;
    delete m2;
}
References ModelIMP::setName().
Referenced by run_Model_unit_test().
test_Model_getEndTime()
void test_Model_getEndTime ()
This function run the unit test of the model getEndTime.
{
    std::cout << "        * getEndTime tests\n";
    Model* m1 = new ModelIMP();
    assert(m1->getEndTime() == 1);
    Model* m2 = new ModelIMP("m2", 0, 2);
    assert(m2->getEndTime() == 2);
    delete m1;
    delete m2;
}
References Model::getEndTime().
Referenced by run_Model_unit_test().
test_Model_getFlows_and_add()
void test_Model_getFlows_and_add ()
This function run the unit test of the model getFlows and add Flow.
{
    std::cout << "        * getFlows and add Flows tests\n";
    Flow* f1 = new Flow_unit_test("f1");
    Model* m1 = new ModelIMP("m1");
    std::vector<Flow*> flows;
    flows.push_back(f1);
    m1->add(f1);
    assert(m1->getFlows() == flows);
    delete f1;
    delete m1;
}
References Model::add(), and Model::getFlows().
Referenced by run_Model_unit_test().
test_Model_getName()
void test_Model_getName ()
This function run the unit test of the model getName.
{
    std::cout << "        * getName tests\n";
    Model* m1 = new ModelIMP();
    assert(m1->getName() == "NO_NAME");
    Model* m2 = new ModelIMP("m2");
    assert(m2->getName() == "m2");
    delete m1;
    delete m2;
}
References Model::getName().
Referenced by run_Model_unit_test().
test_Model_getStartTime()
void test_Model_getStartTime ()
This function run the unit test of the model getStartTime.
{
    std::cout << "        * getStartTime tests\n";
    Model* m1 = new ModelIMP();
    assert(m1->getStartTime() == 0);
    Model* m2 = new ModelIMP("m2", 1);
    assert(m2->getStartTime() == 1);
    delete m1;
    delete m2;
}
References Model::getStartTime().
Referenced by run_Model_unit_test().
test_Model_getSystems_and_add()
void test_Model_getSystems_and_add ()
This function run the unit test of the model getSystems and add System.
{
    std::cout << "        * getSystems and add Systems tests\n";
    System* s1 = new SystemIMP("s1");
    Model* m1 = new ModelIMP("m1");
    std::vector<System*> systems;
    systems.push_back(s1);
    m1->add(s1);
    assert(m1->getSystems() == systems);
    delete s1;
    delete m1;
}
References Model::add(), and Model::getSystems().
Referenced by run_Model_unit_test().
test_Model_rmv_Flow()
void test_Model_rmv_Flow ()
This function run the unit test of the model rmv Flow.
{
    std::cout << "        * Remove Flow tests\n";
    Model* model1 = new ModelIMP();
    FlowIMP* flow1 = new Flow_unit_test("flow1");
    model1->add(flow1);
    assert(model1->rmv(flow1));
    delete model1;
    delete flow1;
}
References Model::add(), and Model::rmv().
Referenced by run_Model_unit_test().
test_Model_rmv_Sytem()
void test_Model_rmv_Sytem ()
This function run the unit test of the model rmv System.
{
    std::cout << "        * Remove System tests\n";
    Model* model1 = new ModelIMP();
    System* system1 = new SystemIMP("system1");
    model1->add(system1);
    assert(model1->rmv(system1));
    delete model1;
    delete system1;
}
References Model::add(), and Model::rmv().
Referenced by run_Model_unit_test().
test_Model_run()
void test_Model_run ()
This function run the unit test of the model run.
                     {
    std::cout << "        * Run tests\n";
    System* s1 = new SystemIMP("s1", 100);
    System* s2 = new SystemIMP("s2", 0.0);
    Flow* f1 = new Flow_unit_test("f1", s1, s2);
    Model* m1 = new ModelIMP("m1", 0, 1);
    m1->add(s1);
    m1->add(s2);
    m1->add(f1);
    m1->run();
    assert(s1->getValue() == 0);
    assert(s2->getValue() == 100);
    delete s1;
    delete s2;
    delete f1;
}
References Model::add(), System::getValue(), and Model::run().
Referenced by run_Model_unit_test().
test_Model_setEndTime()
void test_Model_setEndTime ()
This function run the unit test of the model setEndTime.
{
    std::cout << "        * setEndTime tests\n";
    Model* m1 = new ModelIMP();
    m1->setEndTime(3);
    assert(m1->getEndTime() != 1);
    Model* m2 = new ModelIMP("m2", 0, 1);
    m2->setEndTime(2);
    assert(m2->getEndTime() == 2);
    delete m1;
    delete m2;
}
References Model::getEndTime(), and Model::setEndTime().
Referenced by run_Model_unit_test().
test_Model_setFlows()
void test_Model_setFlows ()
This function run the unit test of the model setFlows.
{
    std::cout << "        * setFlows tests\n";
    Flow* f1 = new Flow_unit_test("f1");
    Model* m1 = new ModelIMP("m1");
    std::vector<Flow*> flows;
    flows.push_back(f1);
    m1->setFlows(flows);
    assert(m1->getFlows() == flows);
    delete f1;
    delete m1;
}
References Model::getFlows(), and Model::setFlows().
Referenced by run_Model_unit_test().
test_Model_setName()
void test_Model_setName ()
This function run the unit test of the model setName.
{
    std::cout << "        * setName tests\n";
    Model* m1 = new ModelIMP();
    m1->setName("m1");
    assert(m1->getName() != "NO_NAME");
    Model* m2 = new ModelIMP("m");
    m2->setName("m2");
    assert(m2->getName() == "m2");
    delete m1;
    delete m2;
}
References Model::getName(), and Model::setName().
Referenced by run_Model_unit_test().
test_Model_setStartTime()
void test_Model_setStartTime ()
This function run the unit test of the model setStartTime.
{
    std::cout << "        * setStartTime tests\n";
    Model* m1 = new ModelIMP();
    m1->setStartTime(3);
    assert(m1->getStartTime() != 0);
    Model* m2 = new ModelIMP("m2", 3);
    m2->setStartTime(1);
    assert(m2->getStartTime() == 1);
    delete m1;
    delete m2;
}
References Model::getStartTime(), and Model::setStartTime().
Referenced by run_Model_unit_test().
test_Model_setSystems()
void test_Model_setSystems ()
This function run the unit test of the model setSystems.
{
    std::cout << "        * setSystems tests\n";
    System* s1 = new SystemIMP("s1");
    Model* m1 = new ModelIMP("m1");
    std::vector<System*> systems;
    systems.push_back(s1);
    m1->setSystems(systems);
    assert(m1->getSystems() == systems);
    delete s1;
    delete m1;
}
References Model::getSystems(), and Model::setSystems().
Referenced by run_Model_unit_test().
test_Model_setTime()
void test_Model_setTime ()
This function run the unit test of the model setTime.
{
    std::cout << "        * setTime tests\n";
    Model* m1 = new ModelIMP();
    m1->setTime(1, 3);
    assert(m1->getStartTime() != 0);
    assert(m1->getEndTime() != 1);
    Model* m2 = new ModelIMP("m2", 0, 1);
    m2->setTime(3, 4);
    assert(m2->getStartTime() == 3);
    assert(m2->getEndTime() == 4);
    delete m1;
    delete m2;
}
References Model::getEndTime(), Model::getStartTime(), and Model::setTime().
Referenced by run_Model_unit_test().