My Vensin: /home/pedro/Downloads/UFOP/Periodo6/EngSoftware1/Engenharia_de_Software1_tp1/tests/unit_tests/src/unit_Flow.cpp File Reference
unit_Flow.cpp File Reference
#include "unit_Flow.h"
Functions
void test_Flow_constructor ()
This function run the unit test of the flow constructor.
void test_Flow_destructor ()
This function run the unit test of the flow destructor.
void test_Flow_getName ()
This function run the unit test of the flow getName.
void test_Flow_getSource ()
This function run the unit test of the flow getSource.
void test_Flow_getTarget ()
This function run the unit test of the flow getTarge.
void test_Flow_setName ()
This function run the unit test of the flow setName.
void test_Flow_setSource ()
This function run the unit test of the flow setSource.
void test_Flow_setTarget ()
This function run the unit test of the flow setTarge.
void test_Flow_execute ()
This function run the unit test of the flow execute.
void test_Flow_equal ()
This function run the unit test of the flow equal comparation.
void run_Flow_unit_test ()
This function run the unit tests of the flow.
Function Documentation
run_Flow_unit_test()
void run_Flow_unit_test ()
This function run the unit tests of the flow.
{
    std::cout << "    Start Flow unit tests\n";
    test_Flow_constructor();
    test_Flow_destructor();
    test_Flow_getName();
    test_Flow_getSource();
    test_Flow_getTarget();
    test_Flow_setName();
    test_Flow_setSource();
    test_Flow_setTarget();
    test_Flow_execute();
    test_Flow_equal();
    std::cout << "    End Flow unit tests\n\n";
}
References test_Flow_constructor(), test_Flow_destructor(), test_Flow_equal(), test_Flow_execute(), test_Flow_getName(), test_Flow_getSource(), test_Flow_getTarget(), test_Flow_setName(), test_Flow_setSource(), and test_Flow_setTarget().
Referenced by main().
test_Flow_constructor()
void test_Flow_constructor ()
This function run the unit test of the flow constructor.
{
    std::cout << "        * Constructor tests\n";
    Flow* f1 = new Flow_unit_test();
    assert(f1->getName() == "NO_NAME");
    assert(f1->getSource() == NULL);
    assert(f1->getTarget() == NULL);
    Flow* f2 = new Flow_unit_test("f2");
    assert(f2->getName() == "f2");
    assert(f2->getSource() == NULL);
    assert(f2->getTarget() == NULL);
    System* s1 = new SystemIMP();
    Flow* f3 = new Flow_unit_test("f3", s1);
    assert(f3->getName() == "f3");
    assert(f3->getSource() == s1);
    assert(f3->getTarget() == NULL);
    System* s2 = new SystemIMP();
    System* s3 = new SystemIMP();
    Flow* f4 = new Flow_unit_test("f4", s2, s3);
    assert(f4->getName() == "f4");
    assert(f4->getSource() == s2);
    assert(f4->getTarget() == s3);
    delete f1;
    delete f2;
    delete s1;
    delete f3;
    delete s2;
    delete s3;
    delete f4;
}
References Flow::getName(), Flow::getSource(), and Flow::getTarget().
Referenced by run_Flow_unit_test().
test_Flow_destructor()
void test_Flow_destructor ()
This function run the unit test of the flow destructor.
{
    std::cout << "        * Destructor tests\n";
    Flow* f1 = new Flow_unit_test();
    f1->~Flow();
}
References Flow::~Flow().
Referenced by run_Flow_unit_test().
test_Flow_equal()
void test_Flow_equal ()
This function run the unit test of the flow equal comparation.
                      {
    std::cout << "        * Equal tests\n";
    FlowIMP* f1 = new Flow_unit_test();
    FlowIMP* f2 = new Flow_unit_test();
    assert(*f1 == *f2);
    f1->setName("f1");
    assert(*f1 != *f2);
    delete f1;
    delete f2;
}
References FlowIMP::setName().
Referenced by run_Flow_unit_test().
test_Flow_execute()
void test_Flow_execute ()
This function run the unit test of the flow execute.
{
    std::cout << "        * Execute tests\n";
    System* s1 = new SystemIMP("s1", 100);
    System* s2 = new SystemIMP("s2", 0.0);
    Flow* f1 = new Flow_unit_test("f1", s1, s2);
    double result = f1->execute();
    f1->getTarget()->setValue(f1->getTarget()->getValue() + result);
    f1->getSource()->setValue(f1->getSource()->getValue() - result);
    assert(s1->getValue() == 0);
    assert(s2->getValue() == 100);
    delete s1;
    delete s2;
    delete f1;
}
References Flow::execute(), Flow::getSource(), Flow::getTarget(), System::getValue(), and System::setValue().
Referenced by run_Flow_unit_test().
test_Flow_getName()
void test_Flow_getName ()
This function run the unit test of the flow getName.
{
    std::cout << "        * getName tests\n";
    Flow* f1 = new Flow_unit_test();
    assert(f1->getName() == "NO_NAME");
    Flow* f2 = new Flow_unit_test("f2");
    assert(f2->getName() == "f2");
    delete f1;
    delete f2;
}
References Flow::getName().
Referenced by run_Flow_unit_test().
test_Flow_getSource()
void test_Flow_getSource ()
This function run the unit test of the flow getSource.
{
    std::cout << "        * getSource tests\n";
    Flow* f1 = new Flow_unit_test();
    assert(f1->getSource() == NULL);
    System* s1 = new SystemIMP();
    Flow* f2 = new Flow_unit_test("f2", s1);
    assert(f2->getSource() == s1);
    delete f1;
    delete s1;
    delete f2;
}
References Flow::getSource().
Referenced by run_Flow_unit_test().
test_Flow_getTarget()
void test_Flow_getTarget ()
This function run the unit test of the flow getTarge.
{
    std::cout << "        * getTarget tests\n";
    Flow* f1 = new Flow_unit_test();
    assert(f1->getTarget() == NULL);
    System* s1 = new SystemIMP();
    System* s2 = new SystemIMP();
    Flow* f2 = new Flow_unit_test("f2", s1, s2);
    assert(f2->getTarget() == s2);
    delete f1;
    delete s1;
    delete s2;
    delete f2;
}
References Flow::getTarget().
Referenced by run_Flow_unit_test().
test_Flow_setName()
void test_Flow_setName ()
This function run the unit test of the flow setName.
{
    std::cout << "        * setName tests\n";
    Flow* f1 = new Flow_unit_test();
    f1->setName("f1");
    assert(f1->getName() != "NO_NAME");
    Flow* f2 = new Flow_unit_test("f");
    f2->setName("f2");
    assert(f2->getName() == "f2");
    delete f1;
    delete f2;
}
References Flow::getName(), and Flow::setName().
Referenced by run_Flow_unit_test().
test_Flow_setSource()
void test_Flow_setSource ()
This function run the unit test of the flow setSource.
{
    std::cout << "        * setSource tests\n";
    System* s1 = new SystemIMP();
    Flow* f1 = new Flow_unit_test();
    f1->setSource(s1);
    assert(f1->getSource() != NULL);
    System* s2 = new SystemIMP();
    Flow* f2 = new Flow_unit_test("f2", s1);
    f2->setSource(s2);
    assert(f2->getSource() == s2);
    delete s1;
    delete s2;
    delete f1;
    delete f2;
}
References Flow::getSource(), and Flow::setSource().
Referenced by run_Flow_unit_test().
test_Flow_setTarget()
void test_Flow_setTarget ()
This function run the unit test of the flow setTarge.
{
    std::cout << "        * setTarget tests\n";
    System* s1 = new SystemIMP();
    Flow* f1 = new Flow_unit_test();
    f1->setTarget(s1);
    assert(f1->getTarget() != NULL);
    System* s2 = new SystemIMP();
    System* s3 = new SystemIMP();
    Flow* f2 = new Flow_unit_test("f2", s1, s2);
    f2->setTarget(s3);
    assert(f2->getTarget() == s3);
    delete s1;
    delete s2;
    delete s3;
    delete f1;
    delete f2;
}
References Flow::getTarget(), and Flow::setTarget().
Referenced by run_Flow_unit_test().