My Vensin: /home/pedro/Downloads/UFOP/Periodo6/EngSoftware1/Engenharia_de_Software1_tp1/tests/unit_tests/src/unit_System.hpp File Reference
unit_System.hpp File Reference
#include "../../../src/SystemIMP.hpp"
#include <assert.h>
Functions
void test_System_constructor ()
This function run the unit test of the system constructor.
void test_System_destructor ()
This function run the unit test of the system destructor.
void test_System_getName ()
This function run the unit test of the system getName.
void test_System_getValue ()
This function run the unit test of the system getValue.
void test_System_setName ()
This function run the unit test of the system setName.
void test_System_setValue ()
This function run the unit test of the system setValeu.
void test_System_equal ()
This function run the unit test of the system equal comparation.
void run_System_unit_test ()
This function run the unit tests of the system.
Function Documentation
run_System_unit_test()
void run_System_unit_test ()
This function run the unit tests of the system.
{
    std::cout << "    Start System unit tests\n";
    test_System_constructor();
    test_System_destructor();
    test_System_getName();
    test_System_getValue();
    test_System_setName();
    test_System_setValue();
    test_System_equal();
    std::cout << "    End System unit tests\n\n";
}
References test_System_constructor(), test_System_destructor(), test_System_equal(), test_System_getName(), test_System_getValue(), test_System_setName(), and test_System_setValue().
Referenced by main().
test_System_constructor()
void test_System_constructor ()
This function run the unit test of the system constructor.
{
    std::cout << "        * Constructor tests\n";
    System* s1 = new SystemIMP();
    assert(s1->getName() == "NO_NAME");
    assert(s1->getValue() == 0.0);
    System* s2 = new SystemIMP("s2");
    assert(s2->getName() == "s2");
    assert(s2->getValue() == 0.0);
    System* s3 = new SystemIMP("s3", 2.0);
    assert(s3->getName() == "s3");
    assert(s3->getValue() == 2.0);
    delete s1;
    delete s2;
    delete s3;
}
References System::getName(), and System::getValue().
Referenced by run_System_unit_test().
test_System_destructor()
void test_System_destructor ()
This function run the unit test of the system destructor.
{
    std::cout << "        * Destructor tests\n";
    System* s1 = new SystemIMP();
    s1->~System();
}
References System::~System().
Referenced by run_System_unit_test().
test_System_equal()
void test_System_equal ()
This function run the unit test of the system equal comparation.
{
    std::cout << "        * Equal tests\n";
    SystemIMP* s1 = new SystemIMP("s1");
    SystemIMP* s2 = new SystemIMP("s2");
    assert(*s1 != *s2);
    SystemIMP* s3 = new SystemIMP();
    SystemIMP* s4 = new SystemIMP();
    assert(*s3 == *s4);
    delete s1;
    delete s2;
    delete s3;
    delete s4;
}
Referenced by run_System_unit_test().
test_System_getName()
void test_System_getName ()
This function run the unit test of the system getName.
{
    std::cout << "        * getName tests\n";
    System* s1 = new SystemIMP();
    assert(s1->getName() == "NO_NAME");
    System* s2 = new SystemIMP("s2");
    assert(s2->getName() == "s2");
    delete s1;
    delete s2;
}
References System::getName().
Referenced by run_System_unit_test().
test_System_getValue()
void test_System_getValue ()
This function run the unit test of the system getValue.
{
    std::cout << "        * getValue tests\n";
    System* s1 = new SystemIMP();
    assert(s1->getValue() == 0);
    System* s2 = new SystemIMP("s2", 22);
    assert(s2->getValue() == 22);
    delete s1;
    delete s2;
}
References System::getValue().
Referenced by run_System_unit_test().
test_System_setName()
void test_System_setName ()
This function run the unit test of the system setName.
{
    std::cout << "        * setName tests\n";
    System* s1 = new SystemIMP();
    s1->setName("s1");
    assert(s1->getName() != "NO_NAME");
    System* s2 = new SystemIMP();
    s2->setName("s2");
    assert(s2->getName() == "s2");
    delete s1;
    delete s2;
}
References System::getName(), and System::setName().
Referenced by run_System_unit_test().
test_System_setValue()
void test_System_setValue ()
This function run the unit test of the system setValeu.
{
    std::cout << "        * setValue tests\n";
    System* s1 = new SystemIMP();
    s1->setValue(21);
    assert(s1->getValue() != 0);
    System* s2 = new SystemIMP("s2", 22);
    s2->setValue(45);
    assert(s2->getValue() == 45);
    delete s1;
    delete s2;
}
References System::getValue(), and System::setValue().
Referenced by run_System_unit_test().