My Vensin: /home/pedro/Downloads/UFOP/Periodo6/EngSoftware1/Engenharia_de_Software1_tp1/tests/unit_tests/src/main.cpp File Reference
main.cpp File Reference
#include "unit_System.hpp"
#include "unit_Flow.hpp"
#include "unit_Model.hpp"
#include "unit_MyVensim.hpp"
Functions
int main ()
Function Documentation
main()
int main ()
          {
    std::cout << "\nStart unit tests\n"
              << "*******************************************************\n";
    run_System_unit_test();
    run_Flow_unit_test();
    run_Model_unit_test();
    run_MyVensim_unit_test();
    std::cout << "*******************************************************\n"
              << "End unit tests\n\n";
    return 0;
}
References run_Flow_unit_test(), run_Model_unit_test(), run_MyVensim_unit_test(), and run_System_unit_test().